In [1]:
import imfusion as imf
from imfusion import vision

import numpy as np
import matplotlib.pyplot as plt


In [2]:
# Load image set with calibration
stereo_images = imf.io.load("data/camera_registration.imf")
# Load marker borad configuration file
marker_config = imf.vision.marker_configuration.load_marker("data/camera_registration_marker_configuration.xml")
# calibration algorithm settings
settings = imf.vision.CameraCalibrationSettings()

In [3]:
result = vision.stereo.register_camera(stereo_images[0], marker_config, settings)

print(f"\nRegistration results:")
print(f"MRE: {result}")
print(f"Left to Right Registration Matrix: {stereo_images[0].components.stereo_calibration.left_to_right_registration}")


Registration results:
MRE: 0.8468761989703671
Left to Right Registration Matrix: [[ 9.99981973e-01 -5.93595925e-04 -5.97500576e-03 -3.35125910e+00]
 [ 5.49341019e-04  9.99972427e-01 -7.40558976e-03  7.67747785e-01]
 [ 5.97923694e-03  7.40217394e-03  9.99954727e-01 -6.76318561e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
