In [ ]:
import imfusion as imf
from imfusion import vision

import numpy as np
import matplotlib.pyplot as plt


In [2]:
# Load image set with calibration
stereo_images = imf.load("data/camera_registration.imf")
# Load marker borad configuration file
marker_config = imf.vision.marker_configuration.load_marker("data/camera_registration_marker_configuration.xml")
# calibration algorithm settings
settings = imf.vision.CameraCalibrationSettings()

In [3]:
result = vision.stereo.register_camera(stereo_images[0], marker_config, settings)

print(f"\nRegistration results:")
print(f"MRE: {result}")
print(f"Left to Right Registration Matrix: {stereo_images[0].components.stereo_calibration.left_to_right_registration}")


Registration results:
MRE: 1.590764388567369
Left to Right Registration Matrix: [[ 9.99981992e-01 -5.92273326e-04 -5.97193321e-03 -3.35167452e+00]
 [ 5.48058625e-04  9.99972450e-01 -7.40267038e-03  7.67477351e-01]
 [ 5.97615308e-03  7.39926411e-03  9.99954767e-01 -6.76643549e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
